version: '3'

services:

  api:
    image: node:fermium-alpine
    build: .
    command: npm run start:dev
    depends_on:
      - mongodb
      - redis
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    networks:
      - rs_ws_env_nw

  mongodb:
    image: mongo:latest
    ports:
      - "17017:27017"
    networks:
      - rs_ws_env_nw

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - rs_ws_env_nw

networks:
  rs_ws_env_nw:
