name: Check

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x

      - run: npm ci
        name: Install

      - run: npm run lint
        name: Lint

      - run: docker-compose up -d mongodb redis
        name: Start infrastructure

      - run:
        name: Tests

      - run: docker-compose down
        name: Dispose infrastructure
