name: Check

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Start infrastructure
        run: docker-compose up -d mongodb redis

      - name: Tests
        run: npm t

      - name: Dispose infrastructure
        run: docker-compose down
